# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [128]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [129]:
A = np.arange(1, 16).reshape(3,5)

In [130]:
print(A)
print("Dimension size: ",A.shape)                       # Dimension size
print("Amount of elements: ",A.size)                    # Amount of elements
print("Datatype of the array's elements:", A.dtype)     # Datatype of the array's elements

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Dimension size:  (3, 5)
Amount of elements:  15
Datatype of the array's elements: int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [131]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print("Default array B: \n", B, "\n")
print("Default array C: \n", C, "\n")


Default array B: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

Default array C: 
 [[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]] 



In [132]:
#Using Numpy to subtract from each element
print("Elementwise subtraction with Numpy: \n", np.subtract(B,C),"\n")

#Using regular B-C
print("Elementwise subtraction without using Numpy: \n", B-C,"\n")

Elementwise subtraction with Numpy: 
 [[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]] 

Elementwise subtraction without using Numpy: 
 [[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]] 



In [133]:
#Using Numpy to multiply from each element
print("Elementwise multiplication with Numpy: \n", np.multiply(B,C),"\n")

#Using regular B*C
print("Elementwise multiplication without using Numpy: \n", B*C,"\n")


Elementwise multiplication with Numpy: 
 [[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]] 

Elementwise multiplication without using Numpy: 
 [[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]] 



In [134]:
# With Numpy
print(np.dot(B, C),"\n")             #Returns the scalar or dot product of two arrays
print(np.matmul(B, C),"\n")          #Returns the matrix product of two arrays

#Without using Numpy - matrix multiplication using @
print("Using @ instead of dot: \n",B @ C)

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]] 

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]] 

Using @ instead of dot: 
 [[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [135]:
B = np.arange(1, 10).reshape(3, 3)
print(B)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [136]:
#Exponentiate
print("Exponentiate: \n",np.exp(B),"\n")

#Minimum
print("Minimum: \n",np.min(B),"\n")

#Minimum on each row - using axis 
print("Minimum on each row: \n",np.min(B, axis = 0),"\n")
print("Minimum on each col: \n",np.min(B, axis = 1),"\n")

#index value for minimum value 
print("index value for minimum value: \n",np.argmin(B, axis = None), "\n")
print("index value for minimum value on each row: \n",np.argmin(B, axis = 1), "\n")

#Calculate sum
print("Calculate sum: \n",np.sum(B), "\n")

#Calculate mean for each columnn
print("Calculate mean for each columnn: \n",np.mean(B, axis = 1), "\n")

#Calculate median for each columnn
print("Calculate median for each columnn: \n",np.median(B, axis = 1), "\n")

Exponentiate: 
 [[   2.7    7.4   20.1]
 [  54.6  148.4  403.4]
 [1096.6 2981.  8103.1]] 

Minimum: 
 1 

Minimum on each row: 
 [1 2 3] 

Minimum on each col: 
 [1 4 7] 

index value for minimum value: 
 0 

index value for minimum value on each row: 
 [0 0 0] 

Calculate sum: 
 45 

Calculate mean for each columnn: 
 [2. 5. 8.] 

Calculate median for each columnn: 
 [2. 5. 8.] 



### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [137]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [138]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [139]:
# You print out the index (Row) but not the value of the all the rows
# 0 is the first row, 1 second etc.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [140]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [141]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [142]:
A = np.arange(1, 16).reshape(3,5)

#List columnwise
print("Columnwise : \n",[[row[i] for row in A] for i in range(len(i))], "\n")

# List elementwise with loop
print("List elementwise: ")
for idx in range(len(A)):
    for j in range(len(A[idx])):
        print(A[idx][j])
        
#Using ravel function to print out a line
print("\nList with ravel: ")
A.ravel()

Columnwise : 
 [[1, 6, 11], [2, 7, 12], [3, 8, 13], [4, 9, 14], [5, 10, 15]] 

List elementwise: 
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15

List with ravel: 


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [143]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print("a: \n",a)
print()

print("B: \n",b)
print(type(b))

a: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

B: 
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
<class 'numpy.ndarray'>


In [144]:
# a is creating 30 elements in an array
# b is reshaping the array into a 3D array with 2x2 elements
# You do not have to specify an exact number for one of the dimensions in the reshape method.
# Pass -1 as the value, and NumPy will calculate this number for you.

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [145]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [146]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [147]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

print(A+b)

[[1 2]
 [3 4]]
[2 2]
[[3 4]
 [5 6]]


# Linear Algebra Exercises

The exercies are taken from the "Matrix Algebra for Engineers" by Chasnov: https://www.math.hkust.edu.hk/~machas/matrix-algebra-for-engineers.pdf .

Do the following exercises: 
* Chapter 2, exercise 1-3.
* Quiz on p.11, exercise 2. 
* Chapter 6, exercise 1. 
* Quiz on p.19, exercise 3. 


* Chapter 10, exercise 1. 
* Chapter 12 exercise 1. 


In [148]:
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])

C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])

E = np.array([[1], [2]])

print(A)
print(B)
print(C)
print(D)
print(E)

[[ 2  1 -1]
 [ 1 -1  1]]
[[ 4 -2  1]
 [ 2 -4 -2]]
[[1 2]
 [2 1]]
[[3 4]
 [4 3]]
[[1]
 [2]]


**Chap2. Question 1.**

**Write a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In this exercise, create a function that takes two matrices as input and either adds or multiplies them by specifying a argument as either 'add' or 'multiply'. Validate that both matrices taken as input are of the type ndarray (use the isinstance function).

In [149]:
def add_mult_matrices(ndarray1,ndarray2,calculate):
    #Check for valid array
    if(isinstance(ndarray1, np.ndarray) & isinstance(ndarray2, np.ndarray)):
       #Check for valid calculation
       if(calculate == 'add' or calculate == 'multiply'):
            if(calculate == 'add'):
                if(np.shape(ndarray1) == np.shape(ndarray2)):
                    print("Adding arrays...")
                    return ndarray1+ndarray2
                else:
                    print("Arrays are not of equal size.")
            elif(calculate == 'multiply'):
                #Columns: len(ndarray1[0]) should equal rows of second input: len(ndarray2)
                if(len(ndarray1[0]) == len(ndarray2)):
                    print("Multiplying arrays")
                    return ndarray1.dot(ndarray2)
                else:
                    raise Exception(f"Rows from 1st array: {len(ndarray2)}, and Colums from 2nd array: {len(ndarray1[0])}, don't have the correct dimensions")     
       else:
           raise ValueError("Choose either 'add' or 'multiply' as methods ") 
    else:
        raise Exception("First two inputs needs to be arrays. ")
    


In [150]:
add_mult_matrices(B,-2*A,'add')

Adding arrays...


array([[ 0, -4,  3],
       [ 0, -2, -4]])

In [151]:
add_mult_matrices(3*C,-E,'add')

Arrays are not of equal size.


In [152]:
add_mult_matrices(A,C,'multiply')

Exception: Rows from 1st array: 2, and Colums from 2nd array: 3, don't have the correct dimensions

In [ ]:
add_mult_matrices(C,D,'multiply')

Multiplying arrays


array([[11, 10],
       [10, 11]])

In [ ]:
add_mult_matrices(C,B,'multiply')

Multiplying arrays


array([[  8, -10,  -3],
       [ 10,  -8,   0]])

**Chap2. Question 2**

In [ ]:
A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])

AB = A.dot(B)
AC = A.dot(C)

#Verify that AB = AC and yet B ̸= C
print(f"AB = AC is {AB.shape == AC.shape}")
print(f"B = C is {B.shape != C.shape}")


AB = AC is True
B = C is False


**Chap2. Question 3**

In [ ]:
A = np.array([[1,1,1],[1,2,3],[1,3,4]])
D = np.array([[2,0,0],[0,3,0],[0,0,4]])

#Compute AD and DA
AD = A.dot(D)
DA = D.dot(A)
print("AD: \n",AD,"\n")
print("DA: \n",DA)

AD: 
 [[ 2  3  4]
 [ 2  6 12]
 [ 2  9 16]] 

DA: 
 [[ 2  2  2]
 [ 3  6  9]
 [ 4 12 16]]


**Quiz p.11, Question 2**

In [ ]:
fir = np.array([[1, -1], [-1, 1]])
sec = np.array([[-1, 1], [1, -1]])

fir.dot(sec)

array([[-2,  2],
       [ 2, -2]])

**Chap 6. Question 1**

In [ ]:
#Find the inverses of the matrices
arr1 = np.array([[5, 6], [4, 5]])
arr2 = np.array([[6, 4], [3, 3]])
inverse1 = np.linalg.inv(arr1)
inverse2 = np.linalg.inv(arr2)

print(inverse1,"\n")
#np.set_printoptions() is used to round floats
np.set_printoptions(suppress=True) 
print(arr1 @ inverse1,"\n")

check = np.allclose(arr1 @ inverse1, np.eye(2))
print(check,"\n")
print("Checking second array...")

print(inverse2,"\n")
np.set_printoptions(precision=1) 
print(arr2 @ inverse2,"\n")

check = np.allclose(arr2 @ inverse2, np.eye(2))
print(check)


[[ 5. -6.]
 [-4.  5.]] 

[[ 1.  0.]
 [-0.  1.]] 

True 

Checking second array...
[[ 0.5 -0.7]
 [-0.5  1. ]] 

[[1. 0.]
 [0. 1.]] 

True


**Quiz p.19, Question 3**

In [ ]:
#Which matrix is the inverse of [2 2],[1 2]?   Stämmer denna verkligen med bokens uppgift eller har jag missat något?
arr3 = np.array([[2, 2], [1, 2]])
inverse3 = np.linalg.inv(arr3)
print(inverse3,"\n")
print(arr3 @ inverse3,"\n")

[[ 1.  -1. ]
 [-0.5  1. ]] 

[[1. 0.]
 [0. 1.]] 



**Chap10. Question 1 a)**

In [ ]:
first = np.array([[3, -7, -2], [-3, 5, 1], [6, -4, 0]])
second = np.array([-7, 5, 2])

gauss = np.linalg.solve(first,second)
print(gauss)
print(first @ gauss)

[ 3.  4. -6.]
[-7.  5.  2.]


**Chap10. Question 1 b)**

In [ ]:
first = np.array([[1, -2, 3], [-1, 3, -1], [2, -5, 5]])
second = np.array([1, -1, 1])

gauss = np.linalg.solve(first,second)
print(gauss)
print(first @ gauss)

[ 8.  2. -1.]
[ 1. -1.  1.]


**Chap 12. Question 1**

In [ ]:
chp12 = np.array([[3, -7, -2], [-3, 5, 1], [6, -4, 0]])
inverse4 = np.linalg.inv(chp12)

check = np.allclose(chp12 @ inverse4, np.eye(3))
np.set_printoptions(precision=1) 
print(inverse4)
print(check)

[[ 0.7  1.3  0.5]
 [ 1.   2.   0.5]
 [-3.  -5.  -1. ]]
True


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [ ]:
v1 = np.arange(4)
##v1 = np.arange(9).reshape(3, 3)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [ ]:
# The base attribute of a view returns the original array while it returns None for a copy.
v1[2:] = [10, 11]
print("V1: ",v1.base)
print("V2: ",v2.base)

V1:  None
V2:  [ 0  1 10 11]


In [ ]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1  10 123]
[ 10 123]


In [ ]:
# Är det en fråga för svaren står ovan ?